name: Pylinter
on: 
    push:
    pull_request: 
    workflow_dispatch:
jobs:
    pylint:
        name: Pylint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                cache: 'pip'

            - name: Install Pylint
              run: |
                python -m pip install --upgrade pip
                pip install pylint 

            - name: Run Pylint
              run: pylint --fail-under=8 ./**/*.py --disable=import-error